
const OUTLET_PRODUCT_MAPPING = {
  NAME: "outlet_products_mapping",
  COLUMNS: {
    ID: "id",
    PRODUCT_ID: "pro_id",
    PRODUCT_CODE: "pro_code",
    OUTLET_ID: "outlet_id",
    OPENING_STOCK: "opening_stock",
    BALENCE_STOCK: "balance_stock",
    MIN_STOCK: "min_stock",
    ALLOW_NEG_STK: "allow_neg_stk",
    OUTLET_PURCHASE: "outlet_purchase",
    OUTLET_NON_SALEABLE: "outlet_non_saleable",
    LOCAL_OUTLET_PURCHASE: "local_outlet_purchase",
    WSCALE: "wscale",
    COMPANY_ID: "company_id",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    IS_INSERTED: "is_inserted",
    MIN_WARN_STOCK: "min_warn_stock",
    PACK_QTY: "pack_qty",
    OUTLET_PRODUCT_ID: "outlet_product_id",
    SUPPLIER_ID: "supplier_id",
    PURCHASE_RATE: "purchase_rate",
    SALES_RATE: "sales_rate",
    MRP: "mrp",
    GST: "gst",
    CESS: "cess",
    HSN: "hsn",
    MBQ: "mbq",
    MBQ_DAYS: "mbqdays",
    PURCHASE_MARGIN: "purchase_margin",
    BARCODE: "barcode",
    BARCODE1: "barcode1",
    BARCODE2: "barcode2",
    BARCODE3: "barcode3",
    BARCODE4: "barcode4",
    GR_WT: "gr_wt",
    MCID: "mcid",
    BCID: "bcid",
    NEGATIVE_STOCK: "negative_stock",
    RATE_EDIT: "rate_edit",
    DECIMAL1: "decimal1",
    ACTIVE: "active",
    LPOINT: "lpoint",
    CPOINT: "cpoint",
    GR_WT: "gr_wt",
    BQTY: "bqty",
    OPQTY: "opqty",
    WEBCHKRATE: "webChkRate",
    POTYPE: "potype",
    COUPON_CODE: "coupon_code",
    UOM_NAME: "uom_name",
    OOSDATE: "oosdate",
    SMARGIN: "smargin",
    CGROUP: "cgroup",
    SH_LIFE: "sh_life",
    WEBRATE: "webrate",
    WEBSTOCK: "webstock",
    SH_LIFEPER: "sh_lifeper",
    WEBCHKRATE: "webchkrate",
    ORDERDAY: "orderday",
    COMCODE: "comcode",
    ONRATE: "onrate",
    STKHOLD: "stkhold",
    POSID: "posid",
    ASUPP: "asupp",
    PARENTID: "parentid",
    TPRODUCT: "tproduct",
    PITEM: "pitem",
    IDATE: "idate",
    PRODLOC: "prodloc",
    PARENT_CODE: "parent_code",
    DIS: "dis",
    PTAX: "ptax",
    STAX: "stax",
    JUICE: "juice",
    REQTY: "reqty",
    MIN_STK_PERIOD: "minstkperiod",
    ORDER_FREQ: "orderfreq",
    SUPPID: "suppid",
    PMARGIN: "pmargin",
    BATCH_NO: "batchno",
    ORDER_QTY: "order_qty",
    BCID: "bcid"
  }
};

const ITEM = {
  NAME: "item",
  COLUMNS: {
    ID: "id",
    PRODUCT_CODE: "pro_code",
    SHORT_NAME: "short_name",
    PRO_DESCRIPTION: "pro_description",
    REGIONAL_NAME: "regional_name",
    PRODUCT_NAME: "pro_name",
    COMPANY_ID: "company_id",
    TYPE_ID: "type_id",
    MAIN_CATEGORY_ID: "main_catgory_id",
    SUB_CATEGORY_ID: "sub_category_id",
    HEAD_ID: "head_id",
    TYPEDESIGN_ID: "typedesign_id",
    MAIN_UOM_ID: "main_uom_id",
    UOM_ID: "uom_id",
    MRP: "mrp",
    PURCHASE_RATE: "pur_rate",
    SALE_RATE: "sale_rate",
    WHOLESALE_RATE: "wholesale_rate",
    GST: "gst",
    CESS: "cess",
    HSN: "hsn",
    OPENING_STOCK: "op_stk",
    MIN_STOCK: "min_stock",
    BALANCE: "balance",
    DNE_BALANCE: "dne_balance",
    INCHARGE_ID: "incharge_id",
    TRAY_ID: "tray_id",
    EXPIRY_TYPE_ID: "expiry_type_id",
    EXPIRY_VALUE: "expiry_value",
    MBQ: "mbq",
    SHRINKAGE: "shrinkage",
    CASE_QTY: "case_qty",
    PUTAWAY: "putaway",
    BULK_ITEM: "bulk_item",
    RETURNABLE_ITEM: "returnable_item",
    PURCHASE: "purchase",
    MIN_STOCK_WARNING: "min_stock_warning",
    BATCH_ITEM: "batch_item",
    ALLOW_NEG_STK: "allow_neg_stk",
    GST_INCLUSIVE: "gst_inclusive",
    WSCALE: "wscale",
    CONVERSION_FACTOR: "convertion_factor",
    DISCOUNT: "discount",
    MAIN_PRODUCT_ID: "main_product_id",
    MAIN_PRODUCT_QTY: "main_product_qty",
    PARENT_PRODUCT_ID: "parent_product_id",
    SESSION_ID: "session_id",
    PRIORITY: "priority",
    PRODUCT_WEIGHT: "product_weight",
    PACK_PRODUCT_ID: "pack_product_id",
    PACK_QTY: "pack_qty",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    IS_INSERTED: "is_inserted",
    MERCHANT_CATEGORY_ID: "merchant_category_id",
    OUTLET_PRODUCT_ID: "outlet_product_id",
    MARGIN: "margin",
    OUTLET_RATE: "outlet_rate",
    SELF_LIFE: "self_life",
    SALES_MARGIN: "sales_margin",
    WAREHOUSE_MARGIN: "warehouse_margin",
    SALES_MARGIN_NEW: "sales_margin_new",
    ORDER_QTY: "order_qty",
    WASTAGE: "wastage",
    OUTLET_PURCHASE: "outlet_purchase",
    IS_INDENT_APPLICABLE: "is_indent_applicable",
    TALLY_UOM: "tally_uom",
    OUTLET_PARENT_ID: "outlet_parent_id",
    VATTYPE: "vattype",
    VATCALC: "vatcalc",
    MCID: "merchant_category_id",
    BCID: "bcid",
    NEGATIVE_STOCK: "negative_stock",
    RATE_EDIT: "rate_edit",
    DECIMAL1: "decimal1",
    ACTIVE: "active",
    LPOINT: "lpoint",
    CPOINT: "cpoint",
    GR_WT: "gr_wt",
    BQTY: "bqty",
    OPQTY: "opqty",
    WEBCHKRATE: "webChkRate",
    POTYPE: "potype",
    COUPON_CODE: "coupon_code",
    UOM_NAME: "uom_name",
    OOSDATE: "oosdate",
    SMARGIN: "sales_margin",
    CGROUP: "cgroup",
    SH_LIFE: "sh_life",
    WEBRATE: "webrate",
    WEBSTOCK: "webstock",
    SH_LIFEPER: "sh_lifeper",
    WEBCHKRATE: "webchkrate",
    ORDERDAY: "orderday",
    COMCODE: "comcode",
    ONRATE: "onrate",
    STKHOLD: "stkhold",
    POSID: "posid",
    ASUPP: "asupp",
    PARENTID: "parentid",
    TPRODUCT: "tproduct",
    PITEM: "pitem",
    IDATE: "idate",
    PRODLOC: "prodloc",
    PARENT_CODE: "parent_code",
    DIS: "discount",
    PTAX: "ptax",
    STAX: "stax",
    JUICE: "juice",
    REQTY: "reqty",
    MIN_STK_PERIOD: "minstkperiod",
    ORDER_FREQ: "orderfreq",
    SUPPID: "suppid",
    PMARGIN: "pmargin",
    BATCH_NO: "batchno",
    ORDER_QTY: "order_qty",
    OLDRATE: "oldrate",
    ITEMADD: "itemadd",
    FIXED_MARGIN: "fixedmargin",
    BARCODE: "barcode",
    BARCODE1: "barcode1",
    BARCODE2: "barcode2",
    BARCODE3: "barcode3",
    BARCODE4: "barcode4",


  }
};

const UNITS = {
  NAME: "units", // confirm your actual table name
  COLUMNS: {
    ID: "id",
    UNITS_SHORT_NAME: "units_short_name",
    UNITS_LONG_NAME: "units_long_name",
    COMPANY_ID: "company_id",
    IS_ACTIVE: "is_active",
    IS_INSERTED: "is_inserted",
    MULTIPLIER: "multiplier",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at"
  }
};
const BARCODE_LIST = {
  NAME: "barcode_list",
  COLUMNS: {
    ID: "id",
    PROD_ID: "prod_id",
    BARCODE: "barcode",
    PRODUCT_CODE: "product_code",
    IS_ACTIVE: "is_active",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    PURCHASE_NO: "purchase_no",
    IS_VERIFIED: "is_verified"
  }
};

const CLEARANCE_SALE = {
  NAME: "clearance_sale",
  COLUMNS: {
    ID: "id",
    DOCNO: "docno",
    DOCDATE: "docdate",
    DOCTIME: "doctime",
    PROD_ID: "prod_id",
    BARCODE: "barcode",
    CQTY: "cqty",
    UQTY: "uqty",
    PRP: "prp",
    SRATE: "srate",
    UID: "uid",
    MRP: "mrp",
  }
};
const PRICEOFF = {
  NAME: 'priceoff',
  COLUMNS: {
    ID: 'id',
    PROD_CODE: 'prod_code',
    AMOUNT: 'amount',
    ETYPE: 'etype',
    PFROM: 'pfrom',
    PTO: 'pto',
    OUTLET: 'outlet',
    PID: 'pid',
    PNAME: 'pname',
    PPARTNER: 'ppartner',
    PCOMPAMT: 'pcompamt',
    PLOCAMT: 'plocamt',
    PACTIVE: 'pactive',
    OID: 'oid',
    DOWNDT: 'downdt',
    STATUS: 'status',
    UID: 'uid',
    PMRP: 'pmrp',
    COMPANY_ID: 'company_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    UPDATED_BY: 'updated_by',
  },
};
const SPL_COUPON = {
  NAME: "spl_coupon",
  COLUMNS: {
    ID: "id",
    SID: "s_id",
    SNAME: "sname",
    SDESC: "sdesc",
    ETYPE: "etype",
    DVALUE: "dvalue",
    PVALUE: "pvalue",
    EFROM: "efrome",
    ETO: "eto",
    ACTIVE: "active",
    MCATE_ID: "mcate_id",
    SCATE_ID: "scate_id",
    PROD_ID: "prod_id",
    MCATE_ID_OFF: "mcate_id_off",
    SCATE_ID_OFF: "scate_id_off",
    PROD_ID_OFF: "prod_id_off",
    CTYPE: "ctype",
    OUTLET_ID: "outlet_id",
    WH_ID: "wh_id",
    COMPANY_ID: "company_id",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    USER_ID: "user_id",
    STATUS: "status",
    SYN_STATUS: "syn_status",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    DOWN_DATE: "down_date",
    PROD: "prod_id",
  }
};
const COUNTER_CART = {
  NAME: "counter_cart",   
  COLUMNS: {
    ID: "id",
    PROD_ID: "prod_id",
    QTY: "qty",
    DISCOUNT_AMOUNT: "discount_amount",
    USERS_ID: "users_id",
    COUNTER_NO: "counter_no",
    CREATED_AT: "created_at",
    MRP: "mrp",
    SALES_RATE: "sales_rate",
    BARCODE: "barcode",
    COUPON_CODE: "coupon_code",
    OUTLET_ID: "outlet_id",
    CUSTOMERS_ID: "customers_id",
    PRODUCTS_CODE: "products_code",
    UNITS_ID: "units_id",
    CART_QUANTITY: "cart_quantity",
    PRODUCTS_RATE: "products_rate",
    PRODUCTS_NAME: "products_name",
    PRODUCTS_OFFER: "products_offer",
    MRP: "mrp",
    SALES_PRICE: "sales_price",
    MINIMUM_SALES_QTY: "minimum_sales_qty",
    MAXIMUM_SALES_QTY: "maximum_sales_qty",
    STOCK_STATUS: "stock_status",
    PACKING_WEIGHT: "packing_weight",
    GST: "gst",
    IGST: "igst",
    CESS: "cess",
    MAIN_CATEGORY_ID: "main_category_id",
    SUB_CATEGORY_ID: "sub_category_id",
    PRODUCTS_ACTIVE: "products_active",
    PRODUCTS_VARIANTS_ACTIVE: "products_variants_active",
    PRODUCTS_STOCK_STATUS: "products_stock_status",
    UNITS_NAME: "units_name",
    PRODUCTS_IMAGES: "products_images",
    UPDATED_AT: "updated_at",
    CATEGORY_NAME: "category_name",
    SUBCATEGORY_NAME: "subcategory_name",
    BRAND_NAME: "brand_name",
    GROUP_NAME: "group_name",
    IS_APPLY_LOYALTY: "is_apply_loyalty",
    CART_TOTAL: "cart_total",
    CART_SUB_TOTAL: "cart_sub_total",
    CART_NET_TOTAL: "cart_net_total",
    REFERENCE_ID: "reference_id",
    TRANSACTION_STATUS : "transaction_status"
  }
};
const COUNTER_CART_TEMP = {
  NAME: "counter_cart_temp",   
  COLUMNS: {
    ID: "id",
    PROD_ID: "prod_id",
    QTY: "qty",
    DISCOUNT_AMOUNT: "discount_amount",
    USERS_ID: "users_id",
    COUNTER_NO: "counter_no",
    CREATED_AT: "created_at",
    MRP: "mrp",
    SALES_RATE: "sales_rate",
    BARCODE: "barcode",
    COUPON_CODE: "coupon_code",
    OUTLET_ID: "outlet_id",
    CUSTOMERS_ID: "customers_id",
    PRODUCTS_CODE: "products_code",
    UNITS_ID: "units_id",
    CART_QUANTITY: "cart_quantity",
    PRODUCTS_RATE: "products_rate",
    PRODUCTS_NAME: "products_name",
    PRODUCTS_OFFER: "products_offer",
    MRP: "mrp",
    SALES_PRICE: "sales_price",
    MINIMUM_SALES_QTY: "minimum_sales_qty",
    MAXIMUM_SALES_QTY: "maximum_sales_qty",
    STOCK_STATUS: "stock_status",
    PACKING_WEIGHT: "packing_weight",
    GST: "gst",
    IGST: "igst",
    CESS: "cess",
    MAIN_CATEGORY_ID: "main_category_id",
    SUB_CATEGORY_ID: "sub_category_id",
    PRODUCTS_ACTIVE: "products_active",
    PRODUCTS_VARIANTS_ACTIVE: "products_variants_active",
    PRODUCTS_STOCK_STATUS: "products_stock_status",
    UNITS_NAME: "units_name",
    PRODUCTS_IMAGES: "products_images",
    UPDATED_AT: "updated_at",
    CATEGORY_NAME: "category_name",
    SUBCATEGORY_NAME: "subcategory_name",
    BRAND_NAME: "brand_name",
    GROUP_NAME: "group_name",
    IS_APPLY_LOYALTY: "is_apply_loyalty",
    CART_TOTAL: "cart_total",
    CART_SUB_TOTAL: "cart_sub_total",
    CART_NET_TOTAL: "cart_net_total",
  }
};

const SPL_COUPON_ISSUE = {
  NAME: "spl_coupon_issue",
  COLUMNS: {
    ID: "id",
    CODE: "code",
    EDATE: "edate",
    DPER: "dper",
    FLAG: "flag",
    DTYPE: "dtype",
    OUTLET_ID: "outlet_id"
  }
}
const SETTING = {
  NAME: "setting",
  COLUMNS: {
    ST_PO_EXP_DAYS: "st_po_exp_days",
    ST_ALLOCT_EXTRA_QTY: "st_alloct_extra_qty",
    ST_DSPTH_BRND_USR: "st_dspth_brnd_usr",
    ST_G_PICK_LOC_ITEM: "st_g_pick_loc_item",
    ST_MALAYSIAN: "st_malaysian",
    ID: "id",
    ST_SALES_PRNT: "st_sales_prnt",
    ST_TERM1: "st_term1",
    ST_TERM2: "st_term2",
    ST_TERM3: "st_term3",
    ST_TERM4: "st_term4",
    ST_TERM5: "st_term5",
    ST_PUR_PRNT: "st_pur_prnt",
    ST_COM_ID: "st_com_id",
    ST_SALES_START: "st_sales_start",
    ST_PUR_START: "st_pur_start",
    ST_PRINT_PRV: "st_print_prv",
    TS_EMAIL1: "ts_email1",
    TS_EMAIL2: "ts_email2",
    TS_EMAIL3: "ts_email3",
    TS_CHK1: "ts_chk1",
    TS_CHK2: "ts_chk2",
    TS_CHK3: "ts_chk3",
    ST_SUPP_RATE: "st_supp_rate",
    ST_CUST_RATE: "st_cust_rate",
    ST_OPN_CASH: "st_opn_cash",
    ST_CASH_BILL_NAME: "st_cash_bill_name",
    ST_CASH_BILL_VAT: "st_cash_bill_vat",
    ST_ONLY_QTY_EDIT: "st_only_qty_edit",
    ST_FOOTER1: "st_footer1",
    ST_FOOTER2: "st_footer2",
    ST_PARENT_STOCK: "st_parent_stock",
    ST_PUR_TYPE: "st_pur_type",
    ST_DAY_EDIT: "st_day_edit",
    ST_CUST_NAME: "st_cust_name",
    ST_MBQ_DAYS: "st_mbq_days",
    ST_PUR_CAPTION: "st_pur_caption",
    ST_SALES_PREFIX: "st_sales_prefix",
    ST_SALES_DC: "st_sales_dc",
    ST_TAMIL_PRINT: "st_tamil_print",
    ST_OUTLET_RATE: "st_outlet_rate",
    ST_SALES_DAYS: "st_sales_days",
    ST_STOCK_DAYS: "st_stock_days",
    ST_MRP_PER: "st_mrp_per",
    ST_STORE_MBQ_PER: "st_store_mbq_per",
    ST_FV_SALES_START: "st_fv_sales_start",
    ST_FV_PUR_START: "st_fv_pur_start",
    ST_EXE_SHARE: "st_exe_share",
    ST_AUTO_EXPORT: "st_auto_export",
    ST_FV_MULTI_DC_SAL: "st_fv_multi_dc_sal",
    ST_EXPIRY_EDIT: "st_expiry_edit",
    ST_SOH_MBQ_PRINT: "st_soh_mbq_print",
    ST_CLOSING_STOCK_VIEW: "st_closing_stock_view",
    ST_MBQ_REGULAR_TYPE: "st_mbq_regular_type",
    ST_WEB_PRD: "st_web_prd",
    ST_MEMO_GRN: "st_memo_grn",
    ST_PO_TERMS: "st_po_terms",
    ST_TRAY_SYNC: "st_tray_sync",
    ST_WH_CASE_QTY_PER: "st_wh_case_qty_per",
    ST_ALLOCT_EXCESS_QTY: "st_alloct_excess_qty",
    ST_FNV_EXTRA_QTY_PER: "st_fnv_extra_qty_per",
    ST_FNV_ALLOCAT_ALERT: "st_fnv_allocat_alert",
    ST_TRAY_ENT_SALES_DESPATCH: "st_tray_ent_sales_despatch",
    ST_TCS_PER: "st_tcs_per",
    ST_TCS_TURN_OVER: "st_tcs_turn_over",
    ST_USER_ROLE: "st_user_role",
    ST_DAY_CLS_TIME: "st_day_cls_time",
    ST_OUTLET_STOCK_MAIL_TIME: "st_outlet_stock_mail_time",
    ST_FNV_DAY_PICK_OUT: "st_fnv_day_pick_out",
    ST_MANUAL_PO_ITEM: "st_manual_po_item",
    ST_BILL_VERIFY: "st_bill_verify",
    ST_FNV_DC_PRINTER: "st_fnv_dc_printer",
    ST_FV_GATE_PASS: "st_fv_gate_pass",
    ST_FV_PO_MAND: "st_fv_po_mand",
    ST_GP_SHIFT: "st_gp_shift",
    ST_GRN_EDIT: "st_grn_edit",
    ST_NO_PO_AUTO_PICK: "st_no_po_auto_pick",
    ST_PUTAWAY_TIME: "st_putaway_time",
    ST_PUTAWAY_CS_TIME: "st_putaway_cs_time",
    ST_FNV_ALLOCT_TIME_BASED: "st_fnv_alloct_time_based",
    MALAYSIA_MRP: "malaysia_mrp",
    MALAYSIA_GST: "malaysia_gst",
    ST_AUTO_SHIFT_START: "st_auto_shift_start",
    ST_FV_TRANSCTION_MENU: "st_fv_transction_menu",
    ST_KITCHEN_MENU: "st_kitchen_menu",
    ST_STORE_MENU: "st_store_menu",
    ST_GS_START: "st_gs_start",
    ST_GT_START: "st_gt_start",
    ST_FS_START: "st_fs_start",
    ST_FT_START: "st_ft_start",
    ST_GSSR_START: "st_gssr_start",
    ST_GTSR_START: "st_gtsr_start",
    ST_FVSR_START: "st_fvsr_start",
    ST_FVPR_START: "st_fvpr_start",
    ST_PR_START: "st_pr_start",
    ST_WST_START: "st_wst_start",
    ST_FVWST_START: "st_fvwst_start",
    ST_FV_PO_DEVIAT: "st_fv_po_deviat",
    ST_LOC_RTV: "st_loc_rtv",
    ST_STORE_CASE_ALLOCATE: "st_store_case_allocate",
    ST_FNV_SEP_DAYCLOSE: "st_fnv_sep_dayclose",
    ST_FMCG_PICK_MRP: "st_fmcg_pick_mrp",
    ST_PUTAWAY_PER: "st_putaway_per",
    ST_LOCATION: "location",
    ACTIVE: "active",

  }
};
const OFFER_MASTER = {
  NAME: "offer_master",
  COLUMNS: {
    OID: "oid",
    OTYPE: "otype",
    ONAME: "oname",
    OBUY: "obuy",
    OGET: "oget",
    PFROM: "pfrom",
    PTO: "pto",
    ACTIVE: "active",
    OBUYID: "obuyid",
    OGETID: "ogetid",
    UID: "uid",
    DIS: "dis",
    POFF: "poff",
    OMODE: "omode",
    OUTLETID: "outletid",
    PPARTNER: "ppartner",
    PCOMPAMT: "pcompamt",
    PLOCAMT: "plocamt",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
};

const OFFER_MASTER_OUTLET = {
  NAME: "offer_master_outlet",
  COLUMNS: {
    ID: "id",
    OID: "oid",
    OUTLET_ID: "outlet_id",
    IS_ACTIVE: "is_active",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
};

const OFFER_MASTER_PARTNER = {
  NAME: "offer_master_partner",
  COLUMNS: {
    ID: "id",
    OID: "oid",
    PPARTNER_ID: "ppartner_id",
    IS_ACTIVE: "is_active",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
};
const OFFER_MASTER_LOGS = {
  NAME: "offer_master_logs",
  COLUMNS: {
    ID: "id",
    OID: "oid",
    OLD_DATA: "old_data",
    CHANGED_DATA: "changed_data",
    OPERATION_NAME: "operation_name",
    COMPANY_ID: "company_id",
    OPERATION_DATE: "operation_date",
    USER_NAME: "user_name",
    USER_ID: "user_id"
  }
};
const OUTLET_SALES_MASTER = {
  NAME: "outlet_sales_master",
  COLUMNS: {
    ID: "id",
    BILL_NO: "billno",
    BILL_DATE: "billdate",
    PARTY_NAME: "customer_name",
    CUSTOMER_ID: "customer_id",
   // UID: "uid",
     GST : "gst",
    AMOUNT: "amount",
    DISCOUNT: "discount",
    CREDIT_CARD: "creditcard",
    COUNTER: "counter_no",
    ROUND_OFF: "roundoff",
    BILLDATE: "bill_date",
    STAX: "stax",
    BAGS: "bags",
    VAT1: "vat1",
    CID: "cid",
    BNO: "bno",
    ROFF: "roff",
    B_AMT: "bamt",
    B_DIS: "bdis",
    B_CASH: "bcash",
    B_CARD: "bcard",
    GLOBAL_DISCOUNT: "gdis",
    V_FLAG: "vflag",
    COUPON: "coupon",
    SCHEME_AMOUNT: "schamt",
    SCHEME_DISCOUNT: "schdis",
    REF_NO: "refno",
    OFFER_AMOUNT: "offamt",
    ORDER_NO: "ordno",
    ONLINE: "online",
    C_B_AMT: "cbamt",
    GIFT: "gift",
    SOURCE_COUPON: "srcoupon",
    SOURCE_VALUE: "srvalue",
    WHATSAPP: "whatsapp",
    STATUS: "status",
    TOTAL_ITEMS: "totitem",
    BARCODE_ITEMS: "baritem",
    GR_WT: "gr_wt",
    GR_TOT: "gr_tot",
    OUTLET_ID: "outlet_id",
    P_MODE: "p_mode",
    REFERENCE_ID : "reference_id",
  }
};
const OUTLET_SALES_DETAIL = {
  NAME: "outlet_sales_details",
  COLUMNS: {
    ID: "id",
    BILL_NO: "billno",
    BNO: "bno",
    BILL_DATE: "billdate",
    BILLDATE: "bill_date",
    COUNTER: "counter",
    SR_ID: "srid",
    CID: "cid",
    PROD_ID: "prod_id",
    PROD_QTY: "prod_qty",
    PROD_RATE: "prod_rate",
    PURCHASE_RATE: "purchase_rate",
    MRP: "mrp",
    VAT: "vat",
    SGST: "sgst",
    CGST: "cgst",
    CESS: "cess",
    DISCOUNT: "dis",
    FQTY: "fqty",
    POFF: "poff",
    BARCODE: "barcode",
    CBAR: "cbar",
    LOYALTY_AMT: "loyalty_amt",
    IDISCOUNT_OFFER_AMT: "idisoff_amt",
    ICOUPON_AMT: "icoup_amt",
    COUPON_AMT: "coup_amt",
    SCHEME_AMT: "sch_amt",
    OFFER_AMT: "off_amt",
    DISCOUNT_AMT: "dis_amt",
    POFF_AMT: "poff_amt",
    OUTLET_ID: "outlet_id",
  }
};
const SCHEMES = {
  NAME: "schemes",
  COLUMNS: {
    SID: "sid",
    SNAME: "sname",
    FDATE: "fdate",
    TDATE: "tdate",
    PAMOUNT: "pamount",
    DTYPE: "dtype",
    DVAL: "dval",
    ACTIVE: "active",
    PID: "pid",
    SMODE: "smode",
    OUTLET_ID: "outlet_id",
    STYPE: "stype",
    CATID: "cat_id",
    QTY: "qty",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
};
const CNT_DENOMINATIONS = {
  NAME: "cnt_denomination",
  COLUMNS: {
    CNT: "cnt",
    UID: "uid",
    EDATE: "edate",
    ETIME: "etime",
    SBILL: "sbill",
    EBILL: "ebill",
    TYPE: "type", // ⚠️ better rename
    N2000: "n2000",
    N500: "n500",
    N200: "n200",
    N100: "n100",
    N50: "n50",
    N20: "n20",
    N10: "n10",
    N5: "n5",
    N1: "n1",
    COIN: "coin",
    CARD: "card",
    UPI: "upi"
  }
};
const CPRTOPTION = {
  NAME: "cprtoption",
  COLUMNS: {
    COUNTER: "counter",
    STATUS: "status",
    DISCOUNT: "discount",
    CASHTENDER: "cashtender",
    CASHCLOSE: "cashclose",
    PENDING: "pending",
    ITEMEDIT: "itemedit",
    CREDITCARD: "creditcard",
    DUPLICATEBILL: "duplicatebill",
    OPNAME: "opname",
    DISPER: "disper",
    BAGS: "bags",
    QTY: "qty",
    PORTSET: "portset",
    CSP: "csp",
    UPISP: "upisp"
  }
};
const COMPANY = {
  NAME: "company",
  COLUMNS: {
    ID: "id",
    CODE: "code",
    SHORTNAME: "company_short_name",
    FULLNAME: "company_fullname",
    ADD1: "add1",
    ADD2: "add2",
    ADD3: "add3",
    ADD4: "add4",
    CITY: "city",
    PINCODE: "pincode",
    STATE: "state",
    COUNTRY: "country",
    PHONE: "phone",
    MOBILE: "mobile",
    EMAIL: "email",
    WEBSITE: "website",
    GSTIN: "gstin",
    FSSAI: "fssai",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    SPLMSG: "splmsg1",
    SPLMSG2: "splmsg2",
  }
};
const COMPANY_BANK_DETAILS = {
  NAME: "company_bank_details",
  COLUMNS: {
    ID: "id",
    COMPANY_ID: "company_id",
    BANKACNO: "bankacno",
    BANKNAME: "bankname",
    ACNAME: "acname",
    IFSCCODE: "ifsccode",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
};
const COMPANY_LOGS = {
  NAME: "company_logs",
  COLUMNS: {
    ID: "id",
    OPERATION_NAME: "operation_name",
    USER_ID: "user_id",
    COMPANY_ID: "company_id",
    COMPANY_NAME: "company_name",
    USER_NAME: "user_name",
    OPERATION_DATE: "operation_date"
  }
};
const SETTING2 = {
  NAME: "setting2",
  COLUMNS: {
    ESYSTEM: "esystem",
    COUNTER: "emailset",
    SMTP: "smtp",
    OEMAIL: "oemail",
    PASS: "pass",
    CASHCLOSE: "cashclose",
    PENDING: "pending",
    ITEMEDIT: "itemedit",
    CREDITCARD: "creditcard",
    DUPLICATEBILL: "duplicatebill",
    OPNAME: "opname",
    DISPER: "disper",
    BAGS: "bags",
    QTY: "qty",
    PORTSET: "portset",
    CSP: "csp",
    UPISP: "upisp"
  }
};
// const SETTING3 = {
//   NAME: "setting3",
//   COLUMNS: {
//     FDATE: "fdate",
//     TDATE: "tdate ",
//     DPER: "dper",
//     ACTIVE: "active",
//     COUPON: "coupon",
//     JDATE: "jdate",
//     JCOUNT: "jcnt",
//     JDIS: "jdis",
//     JCODE: "jcode",
//     MDA: "mda",
//     CATLEVEL: "catlevel",
//     //...
//     DISPER: "disper",
//     BAGS: "bags",
//     QTY: "qty",
//     PORTSET: "portset",
//     CSP: "csp",
//     UPISP: "upisp"
//   }
// }
const OFFER_DETAIL = {
  NAME: "offer_detail",
  COLUMNS: {
    EDATE: "edate",
    CNT: "cnt",
    BNO: "bno",
    PID: "pid",
    OQTY: "oqty",
    PRATE: "prate"
  }
};
const MAIN_CATEGORY = {
  NAME: "main_category",
  COLUMNS: {
    ID: "id",
    CATEGORY_NAME: "category_name",
    CATEGORY_IMAGE: "category_image",
    COMPANY_ID: "company_id",
    IS_ACTIVE: "is_active"
  }
};


const MAIN_CATEGORY_LOGS = {
  NAME: "main_category_logs",
  COLUMNS: {
    ID: "id",
    OPERATION_NAME: "operation_name",
    USER_ID: "user_id",
    CATEGORY_ID: "category_id",
    CATEGORY_NAME: "category_name",
    USER_NAME: "user_name",
    OPERATION_DATE: "operation_date"
  }
};

const SUB_CATEGORY = {
  NAME: "sub_category",
  COLUMNS: {
    ID: "id",
    SUBCATEGORY_NAME: "subcategory_name",
    CATEGORY_ID: "category_id",
    SUBCATEGORY_IMAGE: "subcategory_image",
    IS_INSERTED: "is_inserted",
    COMPANY_ID: "company_id",
    IS_ACTIVE: "is_active"
  }
};

const SESSIONS = {
  NAME: "sessions",
  COLUMNS: {
    ID: "id",
    NAME: "name",
    COMPANY_ID: "com_id",
    ST_TIME: "st_time"
  }
};
const BRANDS = {
  NAME: "brands",
  COLUMNS: {
    ID: "id",
    BRAND_NAME: "brand_name",
    BRAND_IMAGE: "brand_image",
    IS_ACTIVE: "is_active"
  }
};
const HEADS = {
  NAME: "heads",
  COLUMNS: {
    ID: "id",
    CATEGORY_NAME: "cateogory_name",
    COMPANY_ID: "company_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    IS_ACTIVE: "is_active",
    IS_INSERTED :"is_inserted",
  }
};

const ITEM_SETTING = {
  NAME: "item_setting",
  COLUMNS: {
    ID: "id",
    CLIENT_ID: "client_id",
    LOC_ID: "loc_id",
    PROD_ID: "prod_id",
    PRO_CODE: "pro_code",
    OUTLET_PRODUCT_ID: "outlet_product_id",
    S_ACTIVE: "s_active",
    P_ACTIVE: "p_active",
    STATUS: "status",
    P_MARGIN: "pmargin",
    BARCODE_ONE: "barcode_one",
    BARCODE_TWO: "barcode_two",
    BARCODE_THREE: "barcode_three",
    STABARCODE_FOUR: "stabarcode_four",
    WH_ID: "wh_id",
    COMPANY_ID: "company_id",
    IS_INSERTED: "is_inserted",
    SYNC_STATUS: "sync_status",
    EDATE: "edate",
    ETIME: "etime",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at"
  }
};
const OUTLETS = {
  NAME: "outlets",
  COLUMNS: {
    ID: "id",
    CODE: "code",
    SHORTNAME: "short_name",
    FULLNAME: "fullname",
    ADD1: "add1",
    ADD2: "add2",
    ADD3: "add3",
    ADD4: "add4",
    CITY_ID: "city_id",
    PINCODE: "pincode",
    STATE_ID: "state_id",
    COUNTRY_ID: "country_id",
    PHONE: "phone",
    MOBILE: "mobile",
    EMAIL: "email",
    WEBSITE: "website",
    GSTIN: "gstin",
    FSSAI: "fssai",
    OUTLETTYPE: "outlet_type",
    BANKACNO: "bankacno",
    BANKNAME: "bankname",
    ACNAME: "acname",
    IFSCCODE: "ifsccode",
    BALANCE: "balance",
    COMPANY_ID: "company_id",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    ISGST: "is_gst",
    FRANCHISETYPE: "franchise_type",
    BALANCE: "balance",
    CREDIT_LIMIT: "credit_limit",
    LIMITATION: "limitation",
    WALLET_BALANCE: "wallet_balance",
    REF_DOC_NO: "ref_doc_no",
    FOR_INDENT: "for_indent",
    WAREHOUSE_ID: "warehouse_id"
  }
};
const PAYTYPE_MASTER = {
    NAME: "pay_type_master",
    COLUMNS: {
        ID: "id",
        PAY_TYPE_NAME: "pay_type_name",
        PAY_TYPE_KEY:"pay_type_key",
        IS_ACTIVE: "is_active",
        CREATED_AT: "created_at",
        UPDATED_AT: "updated_at",
        CREATED_BY: "created_by",
        UPDATED_BY: "updated_by",
    }
};
const OUTLET_MEMBERS = {
    NAME: "outlet_members",
    COLUMNS: {
        ID: "id",
        MOBILE: "mobile",
        PARTY_NAME: "party_name",
        EMAIL:"email",
        GST_IN: "gst_in",
        BALANCE_POINTS: "balance_points",
        WALLET_AMOUNT: "wallet_amount",
        IS_ACTIVE: "is_active",
        CREATED_BY: "created_by",
        UPDATED_BY: "updated_by",
        CREATED_AT: "created_at",
        UPDATED_AT: "updated_at"
    }
};
const SETTING3 = {
  NAME: "setting3",
  COLUMNS: {
    FDATE: "fdate",
    TDATE: "tdate",
    DPER: "dper",
    ACTIVE: "active",
    COUPON: "coupon",
    JDATE: "jdate",
    JCNT: "jcnt",
    JDIS: "jdis",
    JCODE: "jcode",
    MDA: "mda",
    CATLEVEL: "catlevel",
    RCNAME: "rcname",
    USAVEOPT: "usaveopt",
    AUDITPAY: "auditpay",
    UPIREF: "upiref",
    VSMS: "vsms",
    VSMSLOC: "vsmsloc",
    PMODE: "pmode",
    POCLQTY: "poclqty",
    PFSSAI: "pfssai",
    ADPWD: "adpwd",
    SRATE: "srate",
    MLINK: "mlink",
    BATCH: "batch",
    PLOGO: "plogo",
    PLEFT: "pleft",
    PTOP: "ptop",
    MOBGRN: "mobgrn",
    SMSCONFIRM: "smsconfirm",
    SMSMIN: "smsmin",
    CUSTDELY: "custdely",
    DMINAMT: "dminamt",
    GRNCR: "grncr",
    EMRP: "emrp",
    WID: "wid",
    NEWVER: "newver",
    SPATH: "spath",

    // From first screenshot (top part)
    DC: "dc",
    PGSTUPD: "pgstupd",
    RTYPE: "rtype",
    RYEAR: "ryear",
    MPAY: "mpay",
    MAPPLCLIENT: "mapplclient",
    APPEXP: "appexp",
    POAUTO: "poauto",
    BATCHSHOW: "batchshow",
    WHTM: "whtm",
    PGROUP: "pgroup"
  }
};
const REDEEM_RANGE = {
  NAME: "redeem_range",
  COLUMNS: {
    ID: "id",
    SRID: "srid",
    PFROM: "pfrom",
    PTO: "pto",
    PAMT : "pamt"
 
  }
};
const OUTLET_PAYMENT_LOGS = {
  NAME: "outlet_payment_logs",

  COLUMNS: {
    ID: "id",
    REFERENCE_ID: "reference_id",
    BILL_NO: "bill_no",
    COUNTER_NO: "counter_no",
    OUTLET_ID: "outlet_id",
    AMOUNT: "amount",
    TRANSACTION_STATUS: "transaction_status",
    RESPONSE_CODE: "response_code",
    RESPONSE_MESSAGE: "response_message",
    CREATED_BY: "created_by",
    PAYMENT_STATUS: "payment_status",
    PROVIDER_ID: "provider_id",
    APPROVAL_CODE: "approval_code",
    REQUEST_PAYLOAD: "request_payload",
    RESPONSE_PAYLOAD: "response_payload",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at"
  }
};

const COUNTER_SETTINGS = {
  NAME: "counter_setting",
  COLUMNS: {
    ID: "id",
    OUTLET_ID: "outlet_id",
    COUNTER_NO: "counter_no",
    PAY_TYPE_ID: "pay_type_id",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at"
  }
};

const PAYMENT_PROVIDERS = {
  NAME: "payment_provider",
  COLUMNS: {
    ID: "id",
    COUNTER_NO: "counter_no",
    OUTLET_ID: "outlet_id",
    PROVIDER_NAME: "provider_name",
    PAY_TYPE_ID: "pay_type_id",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by"
  }
}

const PAY_TYPE_MASTER = {
  NAME: "pay_type_master",
  COLUMNS: {
    ID: "id",
    PAY_TYPE_NAME: "pay_type_name",
    PAY_TYPE_KEY: "pay_type_key",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
  }
};

const PAYMENT_PROVIDER_DEVICE_CONFIG = {
  NAME: "payment_provider_device_config",
  COLUMNS: {
    ID: "id",
    PAYMENT_PROVIDER_ID: "payment_provider_id",
    STORE_ID: "store_id",
    MERCHANT_ID: "merchant_id",
    TERMINAL_ID: "terminal_id",
    API_KEY: "api_key",
    SECRET_KEY: "secret_key",
    DEVICE_SERIAL_NO: "device_serial_no",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at"
  }
};
module.exports = {
  OUTLET_PRODUCT_MAPPING,
  UNITS,
  ITEM,
  BARCODE_LIST,
  CLEARANCE_SALE,
  PRICEOFF,
  SPL_COUPON,
  COUNTER_CART,
  COUNTER_CART_TEMP,
  SPL_COUPON_ISSUE,
  SETTING,
  OFFER_MASTER,
  OFFER_MASTER_OUTLET,
  OFFER_MASTER_PARTNER,
  OFFER_MASTER_LOGS,
  // BILL_MASTER,
  ITEM_SETTING,
  SCHEMES,
  CNT_DENOMINATIONS,
  CPRTOPTION,
  COMPANY,
  COMPANY_BANK_DETAILS,
  COMPANY_LOGS,
  SETTING3,
  OFFER_DETAIL,
  OUTLET_SALES_DETAIL,
  OUTLET_SALES_MASTER,
  MAIN_CATEGORY,
  MAIN_CATEGORY_LOGS,
  SUB_CATEGORY,
  SESSIONS,
  BRANDS,
  OUTLETS,
  PAYTYPE_MASTER,
  OUTLET_MEMBERS,
  REDEEM_RANGE,
  HEADS,
  OUTLET_PAYMENT_LOGS,
  COUNTER_SETTINGS,
  PAYMENT_PROVIDERS,
  PAY_TYPE_MASTER,
  PAYMENT_PROVIDER_DEVICE_CONFIG

};
