const { errorSchemas } = require("../../commons/schemas/errorSchemas");
const companyInfoSchema = {
  tags: ["COMPANY INFO"],
  summary: "This API is to get company information",
  headers: { $ref: "request-headers#" },
  response: {
    200: {
      type: "object",
      properties: {
        Cid: { type: "integer" },
        SName: { type: "string" },
        Fname: { type: "string" },
        Add1: { type: "string" },
        Add2: { type: "string" },
        City: { type: "string" },
        Head1: { type: "string" },
        Head2: { type: "string" },
        Phone: { type: "string" },
        Tngst: { type: "string" },
        fssai: { type: "string" },
        splmsg1: { type: "string" },
        splmsg2: { type: "string" },
        // settings: {
        //   type: "object",
        //   properties: {
        //     FTP: { type: "integer" },
        //     EMins: { type: "integer" },
        //     FTPServer: { type: "string" },
        //     FTPUser: { type: "string" },
        //     FTPPasswd: { type: "string" },
        //     FTPPath: { type: "string" },
        //     Master: { type: "integer" },
        //     Rate: { type: "integer" },
        //     pver: { type: "number" },
        //     FTPClient: { type: "string" },
        //     FTPLocal: { type: "integer" },
        //     sreturn: { type: "string" },
        //     Cbilledit: { type: "string" },
        //     prodtype: { type: "integer" },
        //     location: { type: "integer" },
        //     bclient: { type: "string" },
        //     sname: { type: "string" },
        //     cname: { type: "string" },
        //     active: { type: "integer" },
        //     Hserial: { type: "string" },
        //     netid: { type: "string" },
        //     Ptype: { type: "string" },
        //     Puser: { type: "string" },
        //     PArea: { type: "string" },
        //     Pdate: { type: "string" },
        //     shortnameT: { type: "string" },
        //     fullnamet: { type: "string" },
        //     add1t: { type: "string" },
        //     add2t: { type: "string" },
        //     cityt: { type: "string" },
        //     cindex: { type: "integer" },
        //     fdate: { type: "string" },
        //     WMMins: { type: "integer" },
        //     WRMins: { type: "integer" },
        //     WCName: { type: "string" },
        //     WIMaster: { type: "integer" },
        //     WIRate: { type: "integer" },
        //     BarNo: { type: "integer" },
        //     barprint: { type: "integer" },
        //     barport: { type: "integer" },
        //     Rateset: { type: "string" },
        //     BillNoType: { type: "integer" },
        //     FixedDis: { type: "integer" },
        //     PrinterMake: { type: "integer" },
        //     Mcard: { type: "integer" },
        //     Plimit: { type: "number" },
        //     PPoint: { type: "number" },
        //     Pamount: { type: "number" },
        //     rpoint: { type: "integer" },
        //     ramount: { type: "number" },
        //     Sodexo: { type: "integer" },
        //     RClear: { type: "integer" },
        //     fpdis: { type: "number" },
        //     edate: { type: "string" },
        //     cashcard: { type: "integer" },
        //     EditRes: { type: "integer" },
        //     Psearch: { type: "integer" },
        //     vatrep: { type: "integer" },
        //     vatdetprint: { type: "integer" },
        //     editstore: { type: "integer" },
        //     ccsms: { type: "integer" },
        //     Psearch1: { type: "integer" },
        //     nc: { type: "string" },
        //     ItemRestrict: { type: "integer" },
        //     CustRate: { type: "integer" },
        //     Wcashcard: { type: "integer" },
        //     LocalClient: { type: "string" },
        //     client: { type: "integer" },
        //     ftpname: { type: "string" },
        //     St_SaveExp: { type: "integer" },
        //     St_SaveExpPath: { type: "string" }
        //   }
        // } //  informed by srini sir on 04-10-2026 10:26:00
      }
    },
    ...errorSchemas
  }
};

module.exports = companyInfoSchema;
