const { errorSchemas } = require("../../commons/schemas/errorSchemas");

const productFetchSchema = {
  tags: ["PRODUCTS INFO"],
  summary: "This API is to get product information",
  headers: { $ref: "request-headers#" },
  body: {
    type: "object",
    required: ["code", "outlet_id"],
    properties: {
      code: { type: "string", pattern: "^[a-zA-Z0-9.]{1,13}$" },
      outlet_id: { type: "integer" }
    }
  },
  response: {
    200: {
      type: "object",
      properties: {
        is_clearence_flag: { type: "boolean" },
        min_stock_waring_message: { type: "string" },
        min_stock_waring_flag: { type: "boolean" },
        prod_id: { type: "integer" },
        prod_code: { type: "string" },
        prod_name: { type: "string" },
        prod_uom: { type: "integer" },
        mrp: { type: "number" },
        original_sales_rate: { type: "number" },
        sales_rate: { type: "number" },
        discount_rate: { type: "number" },
        purchase_rate: { type: "number" },
        uom_name: { type: "string" },
        qty: { type: "number" },
        sgst: { type: "number" },
        cgst: { type: "number" },
        cess: { type: "number" },
        Vattype: { type: "integer" },
        vatcalc: { type: "integer" },
        mcid: { type: "integer" },
        bcid: { type: "integer" },
        negative_stock: { type: "integer" },
        rate_edit: { type: "integer" },
        decimal1: { type: "integer" },
        Wscale: { type: "integer" },
        active: { type: "integer" },
        LPoint: { type: "integer" }
      }

     
      // properties: {
      //   prod_id: { type: "integer" },
      //   prod_code: { type: "string" },
      //   prod_Name: { type: "string" },
      //   parent_code: { type: "integer" },
      //   prod_uom: { type: "integer" },
      //   Ptax: { type: "number" },
      //   Stax: { type: "number" },
      //   purchase_rate: { type: "number" },
      //   sales_rate: { type: "number" },
      //   mrp: { type: "number" },
      //   balance: { type: "number" },
      //   active: { type: "integer" },
      //   barcode: { type: "string" },
      //   min_stock: { type: "number" },
      //   opening_stock: { type: "number" },
      //   min_warn: { type: "integer" },
      //   negative_stock: { type: "integer" },
      //   prod_path: { type: "string" },
      //   rate_edit: { type: "integer" },
      //   decimal1: { type: "integer" },
      //   oldrate: { type: "number" },
      //   Itemadd: { type: "integer" },
      //   Wscale: { type: "integer" },
      //   juice: { type: "integer" },
      //   prod_namet: { type: "string" },
      //   BatchNo: { type: "integer" },
      //   Vattype: { type: "integer" },
      //   vatcalc: { type: "integer" },
      //   Loc: { type: "integer" },
      //   Wholesale_Rate: { type: "number" },
      //   cid: { type: "integer" },
      //   ReQty: { type: "number" },
      //   MinStkPeriod: { type: "integer" },
      //   OrderFreq: { type: "integer" },
      //   Suppid: { type: "integer" },
      //   Orderday: { type: "string" },
      //   pmargin: { type: "number" },
      //   comcode: { type: "string" },
      //   stkhold: { type: "number" },
      //   bid: { type: "integer" },
      //   posid: { type: "integer" },
      //   Asupp: { type: "string" },
      //   qty: { type: "number" },
      //   parentId: { type: "integer" },
      //   TProduct: { type: "integer" },
      //   PItem: { type: "integer" },
      //   barcode1: { type: "string" },
      //   barcode2: { type: "string" },
      //   barcode3: { type: "string" },
      //   barcode4: { type: "string" },
      //   sgst: { type: "number" },
      //   cgst: { type: "number" },
      //   cess: { type: "number" },
      //   idate: { type: "string", format: "datetime" },
      //   prodloc: { type: "string" },
      //   dis: { type: "number" },
      //   pactive: { type: "integer" },
      //   pmrp: { type: "integer" },
      //   mcid: { type: "integer" },
      //   onrate: { type: "number" },
      //   oosdate: { type: "string" },
      //   bcid: { type: "integer" },
      //   LPoint: { type: "integer" },
      //   CPoint: { type: "integer" },
      //   SMargin: { type: "number" },
      //   cgroup: { type: "integer" },
      //   sh_life: { type: "integer" },
      //   WebRate: { type: "number" },
      //   WebStock: { type: "number" },
      //   Sh_LifePer: { type: "integer" },
      //   Gr_Wt: { type: "number" },
      //   bqty: { type: "integer" },
      //   opqty: { type: "integer" },
      //   WebChkRate: { type: "number" },
      //   Potype: { type: "integer" }
      // }
    },
    ...errorSchemas
  }
};

module.exports = productFetchSchema;
