const PRICEOFF = {
  NAME: 'priceoff',
  COLUMNS: {
    ID: 'id',
    PROD_CODE: 'prod_code',
    AMOUNT: 'amount',
    ETYPE: 'etype',
    PFROM: 'pfrom',
    PTO: 'pto',
    OUTLET: 'outlet',
    PID: 'pid',
    PNAME: 'pname',
    PPARTNER: 'ppartner',
    PCOMPAMT: 'pcompamt',
    PLOCAMT: 'plocamt',
    PACTIVE: 'pactive',
    OID: 'oid',
    DOWNDT: 'downdt',
    STATUS: 'status',
    UID: 'uid',
    PMRP: 'pmrp',
    COMPANY_ID: 'company_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    UPDATED_BY: 'updated_by',
  },
};

const PRICEOFF_OUTLET = {
  NAME: 'priceoff_outlet',
  COLUMNS: {
    ID: 'id',
    PRICEOFF_ID: 'priceoff_id',
    OUTLET_ID: 'outlet_id',
    IS_ACTIVE: 'is_active',
    COMPANY_ID: 'company_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    UPDATED_BY: 'updated_by',
  },
};

const PRICEOFF_PARTNER = {
  NAME: 'priceoff_partner',
  COLUMNS: {
    ID: 'id',
    PRICEOFF_ID: 'priceoff_id',
    PPARTNER_ID: 'ppartner_id',
    IS_ACTIVE: 'is_active',
    COMPANY_ID: 'company_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    UPDATED_BY: 'updated_by',
  },
};

const PRICEOFF_LOGS = {
  NAME: 'priceoff_logs',
  COLUMNS: {
    ID: 'id',
    PRICEOFF_ID: 'priceoff_id',
    OLD_DATA: 'old_data',
    CHANGED_DATA: 'changed_data',
    OPERATION_NAME: 'operation_name',
    COMPANY_ID: 'company_id',
    OPERATION_DATE: 'operation_date',
    USER_NAME: 'user_name',
    USER_ID: 'user_id',
  },
};
const ITEM = {
  NAME: "item",
  COLUMNS: {
    ID: "id",
    PRODUCT_CODE: "pro_code",
    SHORT_NAME: "short_name",
    PRO_DESCRIPTION: "pro_description",
    REGIONAL_NAME: "regional_name",
    PRODUCT_NAME: "pro_name",
    COMPANY_ID: "company_id",
    TYPE_ID: "type_id",
    MAIN_CATEGORY_ID: "main_catgory_id",
    SUB_CATEGORY_ID: "sub_category_id",
    HEAD_ID: "head_id",
    TYPEDESIGN_ID: "typedesign_id",
    MAIN_UOM_ID: "main_uom_id",
    UOM_ID: "uom_id",
    MRP: "mrp",
    PURCHASE_RATE: "pur_rate",
    SALE_RATE: "sale_rate",
    WHOLESALE_RATE: "wholesale_rate",
    GST: "gst",
    CESS: "cess",
    HSN: "hsn",
    OPENING_STOCK: "op_stk",
    MIN_STOCK: "min_stock",
    BALANCE: "balance",
    DNE_BALANCE: "dne_balance",
    INCHARGE_ID: "incharge_id",
    TRAY_ID: "tray_id",
    EXPIRY_TYPE_ID: "expiry_type_id",
    EXPIRY_VALUE: "expiry_value",
    MBQ: "mbq",
    SHRINKAGE: "shrinkage",
    CASE_QTY: "case_qty",
    PUTAWAY: "putaway",
    BULK_ITEM: "bulk_item",
    RETURNABLE_ITEM: "returnable_item",
    PURCHASE: "purchase",
    MIN_STOCK_WARNING: "min_stock_warning",
    BATCH_ITEM: "batch_item",
    ALLOW_NEG_STK: "allow_neg_stk",
    GST_INCLUSIVE: "gst_inclusive",
    WSCALE: "wscale",
    CONVERSION_FACTOR: "convertion_factor",
    DISCOUNT: "discount",
    MAIN_PRODUCT_ID: "main_product_id",
    MAIN_PRODUCT_QTY: "main_product_qty",
    PARENT_PRODUCT_ID: "parent_product_id",
    SESSION_ID: "session_id",
    PRIORITY: "priority",
    PRODUCT_WEIGHT: "product_weight",
    PACK_PRODUCT_ID: "pack_product_id",
    PACK_QTY: "pack_qty",
    IS_ACTIVE: "is_active",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    CREATED_BY: "created_by",
    UPDATED_BY: "updated_by",
    IS_INSERTED: "is_inserted",
    MERCHANT_CATEGORY_ID: "merchant_category_id",
    OUTLET_PRODUCT_ID: "outlet_product_id",
    MARGIN: "margin",
    OUTLET_RATE: "outlet_rate",
    SELF_LIFE: "self_life",
    SALES_MARGIN: "sales_margin",
    WAREHOUSE_MARGIN: "warehouse_margin",
    SALES_MARGIN_NEW: "sales_margin_new",
    ORDER_QTY: "order_qty",
    WASTAGE: "wastage",
    OUTLET_PURCHASE: "outlet_purchase",
    IS_INDENT_APPLICABLE: "is_indent_applicable",
    TALLY_UOM: "tally_uom",
    OUTLET_PARENT_ID: "outlet_parent_id",
    VATTYPE: "vattype",
    VATCALC: "vatcalc",
    MCID: "merchant_category_id",
    BCID: "bcid",
    NEGATIVE_STOCK: "negative_stock",
    RATE_EDIT: "rate_edit",
    DECIMAL1: "decimal1",
    ACTIVE: "active",
    LPOINT: "lpoint",
    CPOINT: "cpoint",
    GR_WT: "gr_wt",
    BQTY: "bqty",
    OPQTY: "opqty",
    WEBCHKRATE: "webChkRate",
    POTYPE: "potype",
    COUPON_CODE: "coupon_code",
    UOM_NAME: "uom_name",
    OOSDATE: "oosdate",
    SMARGIN: "sales_margin",
    CGROUP: "cgroup",
    SH_LIFE: "sh_life",
    WEBRATE: "webrate",
    WEBSTOCK: "webstock",
    SH_LIFEPER: "sh_lifeper",
    WEBCHKRATE: "webchkrate",
    ORDERDAY: "orderday",
    COMCODE: "comcode",
    ONRATE: "onrate",
    STKHOLD: "stkhold",
    POSID: "posid",
    ASUPP: "asupp",
    PARENTID: "parentid",
    TPRODUCT: "tproduct",
    PITEM: "pitem",
    IDATE: "idate",
    PRODLOC: "prodloc",
    PARENT_CODE: "parent_code",
    DIS: "discount",
    PTAX: "ptax",
    STAX: "stax",
    JUICE: "juice",
    REQTY: "reqty",
    MIN_STK_PERIOD: "minstkperiod",
    ORDER_FREQ: "orderfreq",
    SUPPID: "suppid",
    PMARGIN: "pmargin",
    BATCH_NO: "batchno",
    ORDER_QTY: "order_qty",
    OLDRATE: "oldrate",
    ITEMADD: "itemadd",
    FIXED_MARGIN: "fixedmargin",
    BARCODE: "barcode",
    BARCODE1: "barcode1",
    BARCODE2: "barcode2",
    BARCODE3: "barcode3",
    BARCODE4: "barcode4",


  }
};

module.exports = {
  PRICEOFF,
  PRICEOFF_OUTLET,
  PRICEOFF_PARTNER,
  PRICEOFF_LOGS,
  ITEM,

};
